import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/hero';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Angus Development</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.mainContainer}>
        <Header></Header>
        <Hero></Hero>
      </main>
    </>
  );
}
