import { useState } from 'react';

import Head from 'next/head';
import Header from '../components/header';
import Hero from '../components/hero';
import About from '../components/About';
import Pricing from '../components/Pricing';
import Contact from '../components/Contact';

import styles from '@/styles/Home.module.css';

export default function Home() {
  const [lightMode, setLightMode] = useState(false);
  return (
    <>
      <Head>
        <title>Angus Development</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.mainContainer}>
        <Header lightMode={lightMode} setLightMode={setLightMode}></Header>
        <Hero lightMode={lightMode}></Hero>
        <About lightMode={lightMode} setLightMode={setLightMode}></About>
        <Pricing lightMode={lightMode} setLightMode={setLightMode}></Pricing>
        <Contact lightMode={lightMode} setLightMode={setLightMode}></Contact>
      </main>
    </>
  );
}
