import Head from 'next/head';
import Header from '../components/header';
import Hero from '../components/hero';
import About from '../components/About';
import Pricing from '../components/Pricing';
import Contact from '../components/Contact';

import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Angus Development</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.mainContainer}>
        <Header></Header>
        <Hero></Hero>
        <About></About>
        <Pricing></Pricing>
        <Contact></Contact>
      </main>
    </>
  );
}
